// val 目标值，val1 实际值
export const mockGaugeData = {
    val: '5.5',
    curGrpNum: 1,
    type_code: 'LX0312',
    index_code_full_type_name: '累计增速目标值',
    unit_name: '%',
    index_full_code: 'F01ZB000401LX0312',
    index_code_full_cname: '地区生产总值_累计增速目标值',
    index_code_cname: '地区生产总值',
    type: 'bar',
    time_freq: 4,
    index_code: 'ZB000401',
    group_code: 'F01',
    group_name: '全部',
    time_code: 2024,
    time_name: 2024,
    val1: '20',
    type_code1: 'LX0303',
    index_code_full_type_name1: '累计增速',
    unit_name1: '%',
    index_full_code1: 'F01ZB000401LX0303',
    index_code_full_cname1: '地区生产总值_累计增速',
    index_code_cname1: '地区生产总值',
    type1: 'bar',
    time_freq1: 5,
    group_code1: 'F01',
    group_name1: '全部',
    time_code1: 20241,
    time_name1: 20241,
};

export default mockGaugeData;
