/*
 * @Author: zhipengHuang
 * @Date: 2024-08-07 19:25:59
 * @LastEditors: zhipengHuang
 * @LastEditTime: 2024-08-07 19:26:44
 * @Description: 
 */
export const trCardMockDataArr = {
    ok: true,
    sign: 4,
    data:[
        {
            unitCode: '',
            val: 1,
            type_code: 'LX0101',
            index_code_full_type_name: '当期值',
            unit_name: '亿元',
            index_full_code: 'F01ZB002502LX0101',
            index_code_full_cname: '省级重点项目投资总额',
            index_code_cname: '带弹窗和选择',
            time_name: '',
            type: null,
            updated_by: null,
            time_freq: null,
            index_code: 'ZB002502',
            group_code: 'F01',
            group_name: '全部',
            explain_code: null,
            region_name: '山西省',
            region_code: '140000',
            last_compare: null,
        },
        {
            unitCode: '',
            val: 2,
            type_code: 'LX0301',
            index_code_full_type_name: '累计值',
            unit_name: '亿元',
            index_full_code: 'F01ZB002510LX0301',
            index_code_full_cname: '省级重点项目累计完成投资',
            index_code_cname: '省级重点项目累计完成投资',
            time_name: '',
            type: null,
            updated_by: null,
            time_freq: null,
            index_code: 'ZB002510',
            group_code: 'F01',
            group_name: '全部',
            explain_code: null,
            region_name: '山西省',
            region_code: '140000',
            last_compare: null,
        },
        {
            unitCode: '',
            val: 3,
            type_code: 'LX0301',
            index_code_full_type_name: '累计值',
            unit_name: '亿元',
            index_full_code: 'F01ZB00250201LX0301',
            index_code_full_cname: '省级重点项目年度计划投资',
            index_code_cname: '省级重点项目年度计划投资',
            time_name: '',
            type: null,
            updated_by: null,
            time_freq: null,
            index_code: 'ZB00250201',
            group_code: 'F01',
            group_name: '全部',
            explain_code: 'F01ZB00250201LX0301',
            region_name: '山西省',
            region_code: '140000',
            last_compare: null,
        },
        {
            unitCode: '',
            val: 4,
            type_code: 'LX0301',
            index_code_full_type_name: '累计值',
            unit_name: '亿元',
            index_full_code: 'F01ZB002509LX0301',
            index_code_full_cname: '省级重点项目年度完成投资',
            index_code_cname: '省级重点项目年度完成投资',
            time_name: '',
            type: null,
            updated_by: null,
            time_freq: null,
            index_code: 'ZB002509',
            group_code: 'F01',
            group_name: '全部',
            explain_code: null,
            region_name: '山西省',
            region_code: '140000',
            last_compare: null,
        },
    ]
}