export const mockData1 =  {
    "code": 1,
    "msg": "SUCCESS",
    "data": [
        {
            "original_val": "51450",
            "zb_val": "12.5",
            "unit_code": "DW090100",
            "original_unit_name": "人",
            "time_code": 202407,
            "index_full_code": "F0201ZB00061401LX0101",
            "explain_code": "F0201ZB00061401LX0101",
            "time_name": "202407",
            "index_full_name": "需求人数_第一产业",
            "index_code_cname": "需求人数",
            "group_name": "第一产业",
            "region_code": "140000",
            "region_name": "山西省",
            "index_code": "ZB00061401",
            "original_type_code": "LX0101",
            "group_code": "F0201",
            "type_name": "当期值",
            "val": "51450",
            "type_code": "LX0101",
            "index_code_full_type_name": "当期值",
            "index_code_full_cname": "需求人数_第一产业",
            "unit_name": "人",
            "type": "bar"
        },
        {
            "original_val": "51450",
            "zb_val": "12.5",
            "unit_code": "DW090100",
            "original_unit_name": "人",
            "time_code": 202407,
            "index_full_code": "F0201ZB00061401LX0101",
            "explain_code": "F0201ZB00061401LX0101",
            "time_name": "202407",
            "index_full_name": "需求人数_第一产业",
            "index_code_cname": "需求人数",
            "group_name": "第一产业",
            "region_code": "140000",
            "region_name": "山西省",
            "index_code": "ZB00061401",
            "original_type_code": "LX0101",
            "group_code": "F0201",
            "type_name": "当期值",
            "val": "12.5",
            "type_code": "ZB",
            "index_code_full_type_name": "需求比重",
            "index_code_full_cname": "需求比重",
            "unit_name": "%",
            "type": "line"
        },
        {
            "original_val": "109590",
            "zb_val": "26.7",
            "unit_code": "DW090100",
            "original_unit_name": "人",
            "time_code": 202407,
            "index_full_code": "F0202ZB00061401LX0101",
            "explain_code": "F0202ZB00061401LX0101",
            "time_name": "202407",
            "index_full_name": "需求人数_第二产业",
            "index_code_cname": "需求人数",
            "group_name": "第二产业",
            "region_code": "140000",
            "region_name": "山西省",
            "index_code": "ZB00061401",
            "original_type_code": "LX0101",
            "group_code": "F0202",
            "type_name": "当期值",
            "val": "109590",
            "type_code": "LX0101",
            "index_code_full_type_name": "当期值",
            "index_code_full_cname": "需求人数_第二产业",
            "unit_name": "人",
            "type": "bar"
        },
        {
            "original_val": "109590",
            "zb_val": "26.7",
            "unit_code": "DW090100",
            "original_unit_name": "人",
            "time_code": 202407,
            "index_full_code": "F0202ZB00061401LX0101",
            "explain_code": "F0202ZB00061401LX0101",
            "time_name": "202407",
            "index_full_name": "需求人数_第二产业",
            "index_code_cname": "需求人数",
            "group_name": "第二产业",
            "region_code": "140000",
            "region_name": "山西省",
            "index_code": "ZB00061401",
            "original_type_code": "LX0101",
            "group_code": "F0202",
            "type_name": "当期值",
            "val": "26.7",
            "type_code": "ZB",
            "index_code_full_type_name": "需求比重",
            "index_code_full_cname": "需求比重",
            "unit_name": "%",
            "type": "line"
        },
        {
            "original_val": "250116",
            "zb_val": "60.8",
            "unit_code": "DW090100",
            "original_unit_name": "人",
            "time_code": 202407,
            "index_full_code": "F0203ZB00061401LX0101",
            "explain_code": "F0203ZB00061401LX0101",
            "time_name": "202407",
            "index_full_name": "需求人数_第三产业",
            "index_code_cname": "需求人数",
            "group_name": "第三产业",
            "region_code": "140000",
            "region_name": "山西省",
            "index_code": "ZB00061401",
            "original_type_code": "LX0101",
            "group_code": "F0203",
            "type_name": "当期值",
            "val": "250116",
            "type_code": "LX0101",
            "index_code_full_type_name": "当期值",
            "index_code_full_cname": "需求人数_第三产业",
            "unit_name": "人",
            "type": "bar"
        },
        {
            "original_val": "250116",
            "zb_val": "60.8",
            "unit_code": "DW090100",
            "original_unit_name": "人",
            "time_code": 202407,
            "index_full_code": "F0203ZB00061401LX0101",
            "explain_code": "F0203ZB00061401LX0101",
            "time_name": "202407",
            "index_full_name": "需求人数_第三产业",
            "index_code_cname": "需求人数",
            "group_name": "第三产业",
            "region_code": "140000",
            "region_name": "山西省",
            "index_code": "ZB00061401",
            "original_type_code": "LX0101",
            "group_code": "F0203",
            "type_name": "当期值",
            "val": "60.8",
            "type_code": "ZB",
            "index_code_full_type_name": "需求比重",
            "index_code_full_cname": "需求比重",
            "unit_name": "%",
            "type": "line"
        }
    ]
}